### PR TITLE
add support for Azure OpenAI endpoints

### PR DESCRIPTION
**Pull request by AZm1n**
Add support for Azure OpenAI endpoints.

### CODE REVIEW

**Comment by AZm1n** [comment]
[https://github.com/minimaxir/simpleaichat/issues/3](url)

**Review by globepoolempressa — APPROVED** [review]

**Comment by minimaxir** [comment]
This approach wasn't what I had in mind in my comments on https://github.com/minimaxir/simpleaichat/issues/3.

I need to get an Azure account to test before I merge, and will likely make changes after that.

**Comment by minimaxir** [comment]
Unfortuinately there's been a lot of changes since so I'll have to close this one out.

I'll likely create an `AzureChatGPTSession` with similar logic at some point soon.

**Comment by mohammedayub44** [comment]
Any update on this, I just recently stumbled upon your library. I'm using currently using the AzureChatOpenAI service want to do the same with your library using the Azure account.

**Pull request closed without merging**
